### ISSUE TITLE
nill pointer dereference when adding to an offline device

### ISSUE THREAD

**Issue by jumoog** [rkosegi/jdownloader-go#24]
Yesterday my jdownloader crashed during the auto-update and wouldn't run when I tried to add links to the instance.

Here is my sample code:

```golang
urls := []string{"https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso"}
_, err := app.device.LinkGrabber().Add(urls, jdownloader.AddLinksOptionPackage("My download"), jdownloader.AddLinksOptionAutostart(true), jdownloader.AddLinksOptionDownloadPassword("My secret password"))
if err != nil {
	app.logger.Fatal("sendToJd", zap.Error(err))
	return
}

```

I got the error `panic serving: runtime error: invalid memory address or nil pointer dereference`

My program gets the client on startup and then runs for a very long time until I add links at some point. As far as I understand it, the device is no longer present and therefore nill happens when links are added. But the error should be caught later during the nill check, not in between when I have no control.

**Comment by rkosegi** [comment]
Hi @jumoog,
thank you for bug report. 
It's something I haven't anticipated at begining, since my mindset was focused on short-lived CLI-based interface, but your use-case is perfectly valid one. I will try to look at it soon.

**Comment by jumoog** [comment]
In the meantime I did some research. It takes a few seconds for the JD API to notice that the device is no longer online. I can also recreate this with https://my.jdownloader.org/.
